-- TABLE & SEQUENCE DROP
DROP SEQUENCE THREVIEW_SEQ;
DROP TABLE THREVIEW;
DROP TABLE MEMBER;
DROP TABLE MEMBER_GRADE;
DROP TABLE THEATER_SEAT;
DROP SEQUENCE THRCODE_SEQ;
DROP TABLE THEATER_RES;
DROP SEQUENCE THCODE_SEQ;
DROP TABLE THEATER;

-- TABLE & SEQUENCE CREATE
CREATE TABLE THEATER (
    thCODE  VARCHAR2(6) PRIMARY KEY,
    thNAME  VARCHAR2(50) NOT NULL,
    thPART  NUMBER(1) NOT NULL,
    thTIME  VARCHAR2(10) NOT NULL,
    thLOC   VARCHAR2(50) NOT NULL,
    thSEAT  VARCHAR2(2) NOT NULL,
    thPRICE NUMBER(9) NOT NULL,
    thIMG1  VARCHAR2(100) NOT NULL,
    thSCHEDULE NUMBER(1) NOT NULL
);

CREATE SEQUENCE THCODE_SEQ
    MAXVALUE 9999
    NOCACHE
    NOCYCLE;

CREATE TABLE THEATER_RES (
    thrCODE VARCHAR2(20) PRIMARY KEY, 
    mID     VARCHAR2(40) NOT NULL,
    thCODE  VARCHAR2(6) NOT NULL REFERENCES THEATER(thCODE),
    thrCNT  NUMBER(3) NOT NULL,
    thrORDERDATE TIMESTAMP NOT NULL,
    thrREVIEW    NUMBER(1), 
    thrTOTPRICE  NUMBER(10) NOT NULL,
    thrDATE      DATE NOT NULL
);

CREATE SEQUENCE THRCODE_SEQ 
    MAXVALUE 9999
    NOCACHE
    NOCYCLE;
    
CREATE TABLE THEATER_SEAT (
    SEATCODE VARCHAR2(4) PRIMARY KEY,
    thrCODE VARCHAR2(20) NOT NULL REFERENCES THEATER_RES(thrCODE)
);
    
CREATE TABLE MEMBER_GRADE (
    GRADE VARCHAR2(10) PRIMARY KEY,
    LOWVI NUMBER(3) NOT NULL,
    HIGHVI NUMBER(3) NOT NULL,
    DISC NUMBER(3) NOT NULL
);

CREATE TABLE MEMBER (
    mID    VARCHAR2(40) PRIMARY KEY,
    mMAIL  VARCHAR2(50) NOT NULL UNIQUE,
    mPW    VARCHAR2(20) NOT NULL,
    mNAME  VARCHAR2(20) NOT NULL,
    mTEL   VARCHAR2(15) NOT NULL UNIQUE,
    mVISIT NUMBER(3) DEFAULT 0 NOT NULL 
);

CREATE SEQUENCE THREVIEW_SEQ 
    MAXVALUE 9999
    NOCACHE
    NOCYCLE;
    
CREATE TABLE THREVIEW (
    thrNUM   NUMBER(4) PRIMARY KEY,
    thrCODE  VARCHAR2(20) NOT NULL, 
    thrTITLE VARCHAR2(50) NOT NULL,
    thrCONTENT VARCHAR2(4000) NOT NULL,
    thrRDATE   DATE NOT NULL
);


SELECT * FROM MEMBER;

